#````````````````````````````````#
#````````````hlRandom````````````#
#````````````````````````````````#
#``````Your teleport plugin``````#
#````````````````````````````````#
#````````````hlRandom````````````#
#````````````````````````````````#

#```````````````````````````````````````````|Generals|```````````````````````````````````````````#
update-checker: true
first-join-teleport: false
lang: en
#```````````````````````````````````````````|Generals|```````````````````````````````````````````#


#```````````````````````````````````````|Teleport Options|```````````````````````````````````````#
-: 2000 #The greatest distance on -#
+: 2000 #The greatest distance on +#

groupradius: 3 #Radius 
#```````````````````````````````````````|Teleport Options|```````````````````````````````````````#


#````````````````````````````````````````````|Blocks|````````````````````````````````````````````#
teleport-blocks:
    - SPONGE
    -
    -
    -
    -
    -
    -
    -
group-blocks:
    - JUKEBOX
    -
    -
    -
    -
    -
    -
    -
buttons:
    - STONE_BUTTON 
    - WOOD_BUTTON 
    -
    -
    -
    -
    -
    -
badblocks: 
    - STATIONARY_WATER
    -
    -
    -
    -
    -
    -
    -
#````````````````````````````````````````````|Blocks|````````````````````````````````````````````#