name: hlRandom
version: 2.0.0
main: pl.mistur.hlrandom.hlRandom
author: mistuR
commands:
    hlrandom:
        description: Basic hlRandom plugin command
        aliases: [hlr]
    rtp:
        description: Teleport player to the random location
        aliases: [randomtp]
permissions:
    hlrandom.*:
        default: op
        children:
            hlrandom.reload: true
            hlrandom.rtp: true
            hlrandom.useteleport: true
            hlrandom.usegroupteleport: true

    hlrandom.reload:
        default: op
    hlrandom.rtp:
        default: op
    hlrandom.useteleport:
        default: true
    hlrandom.usegroupteleport:
        default: true
    